#!/usr/bin/env php
<?php declare(strict_types=1);

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use AboAdel\VHost\Cmd\{AddVH, Interactive};

use Symfony\Component\Console\Application;

$app = new Application('xamp-vh', '1.0.0');

$app->add(new Interactive('i'));
$app->add(new AddVH('add'));

$app->run();